#!/bin/bash

PROJECT_DIR=${HOME}/projects
remote=jbm@saiety.local

project_name=$1

d=${PROJECT_DIR}/${project_name}

VFLAG=""
[ $DEBUG ] && VFLAG="-v"


[ $DEBUG ] && echo "Working ${project_name} in ${PROJECT_DIR}."

mkdir -p $VFLAG $d
pushd $d &> /dev/null

echo "Initializing git repository for ${project_name}..."
git init

[ $DEBUG ] && echo "Copying in skeleton project..."
cp -r $VFLAG ${PROJECT_DIR}/.skel/* .


[ $DEBUG ] && echo "Creating remote repository..."
ssh ${remote} init_repo.sh ${project_name}
git remote add origin ssh://${remote}/~/gitrepos/${project_name}.git
git add README
git commit -m 'Adds empty README'
git push -u origin master
git pull origin master

popd &> /dev/null
