#!/bin/bash

eval $(undertake config | grep -v '^#')

project_name=$1

d=${UT_PROJECT_DIR}/${project_name}

VFLAG=""
[ $DEBUG ] && VFLAG="-v"


[ $DEBUG ] && echo "Working ${project_name} in ${UT_PROJECT_DIR}."

mkdir -p $VFLAG $d
pushd $d &> /dev/null

echo "Initializing git repository for ${project_name}..."
git init

[ $DEBUG ] && echo "Copying in skeleton project..."
cp -r $VFLAG ${UT_PROJECT_DIR}/.skel/* .


[ $DEBUG ] && echo "Creating remote repository..."
echo $(${UT_REMOTE_GIT_SETUPCMD} ${project_name}) &> /dev/null
git remote add origin ssh://${UT_REMOTE_GIT_BASEURL}/${UT_REMOTE_GIT_BASEPATH}/${project_name}.git
git add README
git commit -m 'Adds empty README'
git push -u origin master
git pull origin master

popd &> /dev/null
