#!/bin/bash

eval $(undertake config | grep -v '^#')

project_name=$1

pushd ${UT_PROJECT_DIR} &> /dev/null

git clone ssh://${UT_REMOTE_GIT_BASEURL}/${UT_REMOTE_GIT_BASEPATH}/${project_name}.git

popd &> /dev/null